# Generated by Django 4.2.16 on 2024-09-25 09:17

from django.db import migrations, models
import people.form_validation


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='age',
        ),
        migrations.AlterField(
            model_name='students',
            name='registration_id',
            field=models.IntegerField(default=0, unique=True, validators=[people.form_validation.registration_validator]),
        ),
    ]
