# Generated by Django 4.2.16 on 2024-09-26 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_teachers_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachers',
            options={'ordering': ['department', 'designation', 'name']},
        ),
    ]
