# Generated by Django 4.2.16 on 2024-09-25 11:47

from django.db import migrations, models
import people.form_validation


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_alter_students_registration_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='registration_id',
            field=models.CharField(max_length=8, unique=True, validators=[people.form_validation.registration_validator]),
        ),
    ]
