# Generated by Django 4.2.16 on 2024-09-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
        ('people', '0004_alter_teachers_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='university.courses'),
        ),
    ]
