# Generated by Django 4.2.16 on 2024-09-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_alter_students_registration_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='password',
            field=models.CharField(default='1234', max_length=500),
        ),
    ]
