# Generated by Django 4.2.16 on 2024-09-25 06:23

from django.db import migrations, models
import django.db.models.deletion
import university.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
                ('department_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.IntegerField(validators=[university.models.age_validator])),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('course', models.ManyToManyField(blank=True, to='university.courses')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.departments')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.IntegerField(validators=[university.models.age_validator])),
                ('date_of_birth', models.DateTimeField()),
                ('course', models.ManyToManyField(blank=True, to='university.courses')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.departments')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.departments'),
        ),
    ]
