# Generated by Django 4.2.16 on 2024-09-25 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='course_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='course_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='departments',
            old_name='department_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='departments',
            old_name='department_name',
            new_name='name',
        ),
    ]
