# Generated by Django 4.2.16 on 2024-09-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_rename_course_code_courses_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ['department', 'name']},
        ),
        migrations.AlterModelOptions(
            name='departments',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['department', 'registration_id']},
        ),
        migrations.AlterModelOptions(
            name='teachers',
            options={'ordering': ['department', 'name']},
        ),
        migrations.AddField(
            model_name='students',
            name='registration_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
