# Generated by Django 4.2.16 on 2024-09-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_alter_courses_options_alter_departments_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
