# Generated by Django 4.2.16 on 2024-09-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_alter_courses_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='designation',
            field=models.CharField(default='Lecturer', max_length=50),
        ),
    ]
